# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute how many days in month M, year Y
#' @description Compute how many days in month M, year Y, as a subfunction for water supply prediction
#' @param Y year
#' @param M month
#' @return Days of Month M in Year Y
#' @examples
#' \dontrun{
#' dates(2022,12)
#' }
#' @export
dates <- function(Y, M) {
    .Call('_StatComp22036_dates', PACKAGE = 'StatComp22036', Y, M)
}

